services:
  redis:
    image: redis:latest
    ports:
      - "6379:6379"
    networks:
      - my_network
  django: &django
    build:
      context: .
      dockerfile: ./Dockerfile
    volumes:
      - ./:/app/
      - ./.env:/app/.env
    ports:
      - 9001:8000
    env_file:
      - ./.env
    depends_on:
      - redis
    networks:
      - my_network
    command: /start
  celeryworker:
    <<: *django
    image: blankon_dashboard_local_celeryworker
    ports: []
    depends_on:
      - redis
    networks:
      - my_network
    command: /start-celeryworker
  celerybeat:
    <<: *django
    image: blankon_dashboard_local_celerybeat
    ports: []
    depends_on:
      - redis
    networks:
      - my_network
    command: /start-celerybeat

networks:
  my_network:
    external: true
